# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/8a7d1b14-cba5-4634-a302-794dd625cee8";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/8D99-DA8C";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/data" = {
      device = "/dev/disk/by-label/home";
      fsType = "ext4";
    };

    "/ubuntu" = {
      device = "/dev/disk/by-label/ubuntu";
      fsType = "ext4";
      options = [ "rw" ];
    };

    "/debian" = {
      device = "/dev/disk/by-label/debian";
      fsType = "ext4";
      options = [ "rw" ];
    };

    "/home" = {
      device = "/debian/home";
      fsType = "none";
      options = [
        "bind"
        "rw"
      ];
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
}
